# Generated by Django 5.2.7 on 2025-10-18 14:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('cluster_id', models.IntegerField(db_index=True)),
                ('algo', models.CharField(default='kmeans', max_length=50)),
                ('k', models.IntegerField()),
                ('features', models.JSONField(default=dict)),
                ('fitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assocrule',
            name='antecedents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='assocrule',
            name='consequents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='assocrule',
            name='conviction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='assocrule',
            name='leverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CustomerCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(db_index=True)),
                ('algo', models.CharField(default='kmeans', max_length=50)),
                ('k', models.IntegerField()),
                ('features', models.JSONField(default=dict)),
                ('fitted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
