# Generated by Django 5.2.7 on 2025-10-18 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_productcluster_alter_assocrule_antecedents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercluster',
            name='customer_key',
            field=models.CharField(db_index=True, default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customercluster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
