# Generated by Django 5.2.7 on 2025-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_customercluster_customer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercluster',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
