# Generated by Django 5.2.7 on 2025-10-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
