# Generated by Django 5.2.7 on 2025-10-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('units_sold', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.FloatField()),
                ('units_returned', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('height_cm', models.CharField(max_length=20)),
                ('weight_kg', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('fitness_level', models.CharField(max_length=50)),
                ('weekly_training', models.CharField(max_length=30)),
                ('training_type', models.CharField(max_length=50)),
                ('supplement', models.CharField(max_length=100)),
                ('supplement_type', models.CharField(max_length=50)),
                ('usage_period_weeks', models.IntegerField()),
                ('usage_frequency_times_week', models.IntegerField()),
                ('diet_type', models.CharField(max_length=50)),
                ('weight_change_kg', models.FloatField()),
                ('body_fat_change', models.FloatField()),
                ('performance_improvement', models.FloatField()),
                ('satisfaction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
            ],
        ),
    ]
