# Generated by Django 5.2.7 on 2025-10-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supplementdata_id_alter_supplementdata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplementData',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
