# Generated by Django 5.2.7 on 2025-10-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_user_to_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
