# Generated by Django 5.2.7 on 2025-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_location_order_platform_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
